### ISSUE TITLE
Characters are replaced by HTML entities

### ISSUE THREAD

**Issue by SebastianZimmer** [editor-js/code#19]
In v2.4.1, reserved HTML characters like `<>&` are replaced by HTML entities on saving data.

Here's a code sandbox to quickly reproduce the issue: https://codesandbox.io/s/peaceful-dhawan-wz02y?file=/index.js

Steps to reproduce:

1. Create code block
2. Type reserved HTML characters like "<>&"
3. Click on "Save and load"

The code block's content changes and displays the HTML entities of the characters.

**Comment by m-alzam** [comment]
Fixed in #20

**Comment by gopumon** [comment]
Is there any workaround till next release??

**Comment by erBhushanPawar** [comment]
You can use this code for getting it fixed, call it after save block returns the data
`fixCodeBlocks(blocks) {

    let codeBlockIndex = 0;
    const els = document.getElementsByClassName('ce-code__textarea') as any || [];
    blocks.map(x => {

      if (x.type === 'code') {
        x.data.code = els[codeBlockIndex].value
      }
      return x;
    })
    return blocks;
  }`
