### ISSUE TITLE
 Output format: Can the 'code' property be null omitted?

### ISSUE THREAD

**Issue by cmeeren** [editor-js/code#38]
For a valid code block, can the `code` property under any circumstances (now or in the future) be `null` or omitted? Or is it guaranteed to always be present and non-`null` for this block to be valid?

Context: I'm a back-end .NET developer needing to parse Editor.js documents. The readme does not explicitly guarantee that `code` will always be present and non-null. Back-end deserialization/parsing in strongly typed languages would be easier with some guarantees about which properties can and can not be null/omitted. (Ideally, any such guarantees should be added to the readme to ensure they are formalized and kept in the future.)

**Comment by cmeeren** [comment]
Could anyone clarify this, please? Thanks! 😊

**Comment by neSpecc** [comment]
The `code` property will always be in a block data. And it always be a string.
