### ISSUE TITLE
The height of the textarea cannot be adapted to the content.

### ISSUE THREAD

**Issue by xiaogonggong-w** [editor-js/code#63]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/79799040/217705972-99f172d3-af33-427b-a0da-b08cf9fd5439.png">

The minimum height is set here

**Comment by SalesforceBobLightning** [comment]
How can we get the textarea to grow automatically to the content size?

**Comment by neSpecc** [comment]
Duplicated #41
