### ISSUE TITLE
Cannot delete text with backspace or navigate with arrow keys in Firefox

### ISSUE THREAD

**Issue by AlexFRAN** [editor-js/code#67]
When you load already saved data into the editor and there is a code-block, you cannot delete characters with backspace (with del you can), neither can you navigate with the arrow-keys inside the code-block. It simply jumps to the block above instantly (in my example a header block).

Example:

```
const editor = new EditorJS({  
        data: {  
        "time":1700475383740,
        "blocks":[
            {"id":"aRMoZePSTD","type":"header","data":{"text":"My title","level":2}},
            {"id":"fcG8CCR5F8","type":"code","data":{"code":"here is some code"}}
        ],
        "version":"2.28.2"
    },
    tools: {
        code: CodeTool,
        header: Header
    }
});
```

Versions:

- editorjs: 2.28.2
- code: 2.9.0
- header: 2.8.1
- esbuild: 0.19.6
- Firefox: 119.0.1

Bundled with: esbuild, like this: ./node_modules/.bin/esbuild src/index.js --bundle --outfile=dist/index.js
Browser: Latest Firefox, it works in Chrome

**Comment by wonder-image** [comment]
Same problem

**Comment by CasFreriks** [comment]
I have also the same problem, is this something worth solving?

**Comment by jigneshzala** [comment]
Facing same issue, any solution?

**Comment by hushulin** [comment]
same issue +1
