### ISSUE TITLE
Accessing data variable in class wrongly. Use _data instead of data

### ISSUE THREAD

**Issue by Prakhar-FF13** [editor-js/code#71]
In class CodeTool:

Current Behaviour:
In getters and setters functions we use this._data.
Whereas in other parts like onPaste function, constructor, drawView , we are using this.data to access the data variable.

Proposed Fix:
Change this.data to this._data everywhere.

Why is this needed?
If we dont do this then when migrating to typescript we get a naming conflict error. As data() getter and data variable are of same name.

**Comment by neSpecc** [comment]
The `data` getter and setter is designed to synchronize stored `_data` with DOM

**Comment by neSpecc** [comment]
The problem is not clear. 

I'll close it. Please, add more details for how to you found the problem. What it affects? I'll reopen if problem will be confirmed
