### ISSUE TITLE
Backspaces do not work when the code block contains initial data.

### ISSUE THREAD

**Issue by yosipy** [editor-js/code#75]
When we add a new code block, backspace works.

https://github.com/user-attachments/assets/975796e4-58d2-4082-8b32-b6ee6b26d5d5

However, when updating a code block with initial data, backspaces do not work.

```ts
      const editorConfig = {
        data: {
          blocks: [
            
            {
              type: "code",
              data: {
                code: 'console.log("ssss")',
              },
            },
          ],
```

https://github.com/user-attachments/assets/9bfecc31-bfb3-4a7d-8c16-9c47e1c42234

**Comment by neSpecc** [comment]
Duplicate #67
